server:
  port: 8080

eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msvc-student
          uri: http://localhost:8090
          predicates:
            - Path=/api/students/**
        - id: msvc-course
          uri: http://localhost:9090
          predicates:
            - Path=/api/courses/**