server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msvc-student
          uri: http://localhost:8090
          predicates:
            - Path=/api/students/**
        - id: msvc-course
          uri: http://localhost:9090
          predicates:
            - Path=/api/courses/**